/* ============================================================
   store.js - 全局状态管理与 localStorage 持久化
   所有数据通过 localStorage 保存，支持导入/导出
   ============================================================ */
const Store={
  KEY:'avn_store_v2',
  state:null,
  def(){
    return{
      settings:{theme:'light',bgMusic:null,bgVolume:0.5,textSpeed:50,autoMode:false,vnMode:'cards'},
      apis:{main:{url:'',key:'',model:'',name:'主API'},assistant:{url:'',key:'',model:'',name:'助手API'}},
      presets:[],
      regexRules:[],
      worldBook:[],
      saves:[],
      currentGame:null,
      characters:[],
      portraits:[],
      backgrounds:[],
      scenes:[],
      musics:[],
      maps:[],
      memories:[],
      memoryCats:[{id:'plot',name:'剧情',color:'#C9A227'},{id:'char',name:'角色',color:'#8B4513'},{id:'item',name:'物品',color:'#4A7C59'},{id:'emo',name:'情感',color:'#B22222'},{id:'loc',name:'地点',color:'#2C1810'},{id:'other',name:'其他',color:'#8B7355'}],
      personas:[],
      chatHistory:[],
      phoneChats:[],
      forumPosts:[],
      emails:[],
      customApps:[],
      relations:[],
      charNotes:{},
      charInv:{},
      interactions:[],
      storylines:[],
      statusFields:[{key:'year',name:'年份',value:'建元元年'},{key:'month',name:'月份',value:'1月'},{key:'time',name:'时辰',value:'清晨'},{key:'money',name:'银两',value:'100000'},{key:'food',name:'粮食',value:'200000'},{key:'hp',name:'体力',value:'100'},{key:'favor',name:'好感',value:'50'},{key:'prestige',name:'威望',value:'0'}],
      customThemes:[],
      lastSaved:Date.now(),
    };
  },
  init(){const s=localStorage.getItem(this.KEY);if(s){try{this.state={...this.def(),...JSON.parse(s)};}catch(e){console.error('Store load err',e);this.state=this.def();}}else{this.state=this.def();}return this.state;},
  save(){this.state.lastSaved=Date.now();try{localStorage.setItem(this.KEY,JSON.stringify(this.state));}catch(e){if(e.name==='QuotaExceededError')Utils.toast('存储空间不足，请清理图片');}},
  exportAll(){return JSON.stringify(this.state,null,2);},
  importAll(str){try{const d=JSON.parse(str);this.state={...this.def(),...d};this.save();return true;}catch(e){console.error(e);return false;}},
  reset(){this.state=this.def();this.save();},
  addChar(c){c.id=c.id||Utils.uid();c.createdAt=Date.now();this.state.characters.push(c);this.save();return c;},
  upChar(id,up){const i=this.state.characters.findIndex(x=>x.id===id);if(i>=0){this.state.characters[i]={...this.state.characters[i],...up};this.save();}},
  delChar(id){this.state.characters=this.state.characters.filter(x=>x.id!==id);this.save();},
  getChar(id){return this.state.characters.find(x=>x.id===id);},
  addPortrait(p){p.id=p.id||Utils.uid();this.state.portraits.push(p);this.save();return p;},
  addBg(b){b.id=b.id||Utils.uid();this.state.backgrounds.push(b);this.save();return b;},
  addScene(s){s.id=s.id||Utils.uid();this.state.scenes.push(s);this.save();return s;},
  addMusic(m){m.id=m.id||Utils.uid();this.state.musics.push(m);this.save();return m;},
  addMap(m){m.id=m.id||Utils.uid();this.state.maps.push(m);this.save();return m;},
  addPreset(p){p.id=p.id||Utils.uid();this.state.presets.push(p);this.save();return p;},
  addWb(e){e.id=e.id||Utils.uid();this.state.worldBook.push(e);this.save();return e;},
  addMem(m){m.id=m.id||Utils.uid();m.timestamp=Date.now();this.state.memories.push(m);if(this.state.memories.length>500)this.state.memories=this.state.memories.slice(-500);this.save();return m;},
  addRel(r){r.id=r.id||Utils.uid();this.state.relations.push(r);this.save();return r;},
  addApp(a){a.id=a.id||Utils.uid();this.state.customApps.push(a);this.save();return a;},
  createSave(name){
    const save={id:Utils.uid(),name:name||`存档 ${this.state.saves.length+1}`,timestamp:Date.now(),game:Utils.deepClone(this.state.currentGame||{}),history:Utils.deepClone(this.state.chatHistory),mem:Utils.deepClone(this.state.memories),chars:Utils.deepClone(this.state.characters)};
    this.state.saves.push(save);this.save();return save;
  },
  loadSave(id){const s=this.state.saves.find(x=>x.id===id);if(s){this.state.currentGame=Utils.deepClone(s.game);this.state.chatHistory=Utils.deepClone(s.history);this.state.memories=Utils.deepClone(s.mem);this.state.characters=Utils.deepClone(s.chars);this.save();return true;}return false;},
  // 别名：pages2.js 兼容
  addCharacter(c){return this.addChar(c);},
  updateCharacter(id,up){return this.upChar(id,up);},
  deleteCharacter(id){return this.delChar(id);},
  deleteRelation(id){this.state.relations=this.state.relations.filter(x=>x.id!==id);this.save();},
  deleteStoryline(id){this.state.storylines=this.state.storylines.filter(x=>x.id!==id);this.save();},
  deleteWorldBookEntry(id){this.state.worldBook=this.state.worldBook.filter(x=>x.id!==id);this.save();},
  deleteRegexRule(id){this.state.regexRules=this.state.regexRules.filter(x=>x.id!==id);this.save();},
  deletePreset(id){this.state.presets=this.state.presets.filter(x=>x.id!==id);this.save();},
  deleteMemory(id){this.state.memories=this.state.memories.filter(x=>x.id!==id);this.save();},
  deletePortrait(id){this.state.portraits=this.state.portraits.filter(x=>x.id!==id);this.save();},
  deleteBackground(id){this.state.backgrounds=this.state.backgrounds.filter(x=>x.id!==id);this.save();},
  deleteMap(id){this.state.maps=this.state.maps.filter(x=>x.id!==id);this.save();},
  deleteMusic(id){this.state.musics=this.state.musics.filter(x=>x.id!==id);this.save();},
  deleteScene(id){this.state.scenes=this.state.scenes.filter(x=>x.id!==id);this.save();},
  deleteCustomApp(id){this.state.customApps=this.state.customApps.filter(x=>x.id!==id);this.save();},
  addCustomApp(a){return this.addApp(a);},
  addRegexRule(r){r.id=r.id||Utils.uid();this.state.regexRules.push(r);this.save();return r;},
  addWorldBookEntry(e){return this.addWb(e);},
};
